services:
  java:
    build:
      context: .
      # ruta al Dockerfile (Por defecto es "Dockerfile") (Por eso "Dockerfile" va con "D" mayuscula)
      # dockerfile: Dockerfile
    ports:
      # izq: puerto del host (servidor, ec2, etc)
      # der: puerto expuesto del contenedor, "donde la app escucha"
      - "8080:8080"
    command: ["java","-jar","app.jar"]
    environment:
      - SPRING_PROFILES_ACTIVE=prod
